version: '3.8'

services:
  app:
    image: discord-bot.py
    build: .
    container_name: discord-bot.py
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./src/:/app/src/