FROM python:3.10-alpine

# Install necessary alpine packages
RUN apk add --no-cache bash vim git ffmpeg

# Set working directory
WORKDIR /app/

# Install required python extensions
RUN pip install --upgrade pip
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade --requirement requirements.txt

COPY ./src/ ./src/
COPY ./chaves.wav /app/

#CMD [ "python", "/app/src/bot.py" ]